/**
 * Created by fs11239 on 12/14/2016.
 */

require.config({
    paths: {
        // jQuery & jQuery UI
        jquery                 : "https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min",
        jqueryPlugin           : "../inc/lib/js/jquery-migrate-1.4.1.min",
        googleCharts           : "https://www.gstatic.com/charts/loader",
        jsCharts               : '../inc/lib/js/Chart',
        jQueryMouseWheel       : '../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/lib/jquery.mousewheel',
        underscore             : '../inc/lib/js/underscore',
        jqueryui               : '../inc/lib/js/SlickGrid-master/lib/jquery-ui-1.8.16.custom.min',
        dragevent              : '../inc/lib/js/SlickGrid-master/lib/jquery.event.drag-2.2',
        dropevent              : '../inc/lib/js/SlickGrid-master/lib/jquery.event.drop-2.2',
        select2                : '../inc/lib/js/select2-4.0.3/dist/js/select2.full',
        bootstrap33  : 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min',

        bootstrapJS            : '../inc/lib/css/bootstrap/js/bootstrap',
        bootbox                : '../inc/lib/css/bootbox.min',
        jQuerysortable         : '../inc/lib/js/jquery.sortable',
        sortable               : "//rubaxa.github.io/Sortable/Sortable",
        //select2      : "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full",
        // SlickGrid
        slickcore              : "../inc/lib/js/SlickGrid-master/slick.core",
        slickCoreFrozen        : "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/slick.core",
        slickPager             : "../inc/lib/js/SlickGrid-master/controls/slick.pager",
        slickPagerFrozen       : "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/controls/slick.pager",
        slickRemotePager       : "../inc/lib/js/SlickGrid-master/plugins/slickgrid.remotepager",
        slickdataviewFrozen    : "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/slick.dataview",
        slickGridFrozen        : "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/slick.grid",
        slickgrid              : "../inc/lib/js/SlickGrid-master/slick.grid",
        slickdataview          : "../inc/lib/js/SlickGrid-master/slick.dataview",
        slickCellCopy          : "../inc/lib/js/SlickGrid-master/plugins/slick.cellcopymanager",
        slickCellRangeDecorator: "../inc/lib/js/SlickGrid-master/plugins/slick.cellrangedecorator",
        slickCheckColumn       : "../inc/lib/js/SlickGrid-master/plugins/slick.checkboxselectcolumn",
        slickRowSelection      : "../inc/lib/js/SlickGrid-master/plugins/slick.rowselectionmodel",
        slickRowSelectionFrozen: "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/plugins/slick.rowselectionmodel",
        slickAutoToolTips      : "../inc/lib/js/SlickGrid-master/plugins/slick.autotooltips",
        slickAutoToolTipsFrozen: "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/plugins/slick.autotooltips",
        cellSelectionModel     : "../inc/lib/js/SlickGrid-master/plugins/slick.cellselectionmodel",
        slickFormatters        : "../inc/lib/js/SlickGrid-master/slick.formatters",
        slickEditors           : "../inc/lib/js/SlickGrid-master/slick.editors",
        firebugx               : "../inc/lib/js/SlickGrid-master/lib/firebugx",
        slickCellRangeSelector : "../inc/lib/js/SlickGrid-master/plugins/slick.cellrangeselector",
        slickColumnPicker      : "../inc/lib/js/SlickGrid-master/controls/slick.columnpicker",
        slickHeaderBtn         : "../inc/lib/js/SlickGrid-master/plugins/slick.headerbuttons",
        slickHeaderBtnFrozen   : "../inc/lib/js/SlickGrid-2.0-frozenRowsAndColumns/plugins/slick.headerbuttons"
        //totalDataView         : "../../inc/lib/js/slickgrid-totals-plugin-master/src/TotalsDataView",
        //totalPlugin         : "../../inc/lib/js/slickgrid-totals-plugin-master/src/TotalsPlugin"
    },
    shim: {
        jqueryPlugin           : ['jquery'],
        jqueryui               : ['jqueryPlugin'],
        jquery                 : ['jqueryPlugin'],
        jquery                 : {exports: '$'},
        underscore             : {exports: '_'},
        jqueryui               : ['jquery'],
        jQueryMouseWheel       : ["jqueryPlugin",'jquery'],
        slickColumnPicker      : ['jquery'],
        slickCellRangeDecorator: ['jquery'],
        cellSelectionModel     : ['jquery', 'slickCellRangeSelector', 'slickCellRangeDecorator'],
        slickCellRangeSelector : ['jquery'],
        dragevent              : ['jquery'],
        dropevent              : ['jquery'],
        slickCellCopy          : ['jquery'],
        slickCheckColumn       : ["slickgrid", 'slickColumnPicker'],
        slickPager             : ['jquery'],
        slickPagerFrozen       : ['jquery'],
        slickRemotePager       : ['jquery'],
        slickAutoToolTipsFrozen: ['jqueryPlugin','jquery'],
        slickAutoToolTips      : ['jquery'],
        slickEditors           : ['jqueryPlugin', 'jquery'],
        jQuerysortable         : ['jquery'],
        slickRowSelectionFrozen: ['jquery'],
        slickRowSelection      : ['jquery'],
        slickHeaderBtn         : ["jqueryPlugin",'jquery'],
        slickHeaderBtnFrozen   : ["jqueryPlugin",'jquery'],
        slickFormatters        : ['jquery'],
        bootstrapJS            : ['jquery'],
        bootstrap33            : ['jquery'],
        bootbox                : ['bootstrapJS'],
        slickcore              : ['jqueryui'],
        slickgrid              : ['slickcore', 'dragevent', 'dropevent', 'underscore'],
        slickGridFrozen        : ['slickcore', 'dragevent', 'dropevent', 'underscore'],
        slickdataview          : ['slickgrid'],
        slickdataviewFrozen    : ['slickgrid']
/*        totalDataView    : ['jquery'],
        totalPlugin     : ['jquery']*/
    }
});
