[Process021]

ProcessID=SQLCommand

SQLCommand=update cawp set eac = 154579.0000, EAC_NONLAB = 154579.0000, PC_COMP = 0.0000 where PROGRAM = '0481' and wp = 'MATL-042-999';update tphase set DIRECT = 7535.5607 where program = '0481' and CAWPID in (-1825950139) and CLASS = 'Forecast';update cawp set eac = 103899.0003, EAC_NONLAB = 103899.0003, PC_COMP = 12.6800 where PROGRAM = '0481' and wp = 'MATL-854-999';update tphase set DIRECT = 4697.1290 where program = '0481' and CAWPID in (2053516204) and CLASS = 'Forecast'
