[Process001]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=Actual
TargetAction=Replace
TargetClass=FF
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process002]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=CA
TargetAction=Add
TargetClass=FF
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process003]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=EA
TargetAction=Add
TargetClass=FF
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process004]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=Forecast
TargetAction=Add
TargetClass=FF
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process005]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=Budget
TargetAction=Replace
TargetClass=PB
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process006]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=Actual
TargetAction=Replace
TargetClass=PA
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process007]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=EA
TargetAction=Replace
TargetClass=PE
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process008]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=Forecast
TargetAction=Replace
TargetClass=PF
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process009]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=RA
TargetAction=Add
TargetClass=PB
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

[Process010]
ProcessID=Reclass
Project=****
SourceAction=Copy
SourceClass=CA
TargetAction=Replace
TargetClass=PCA
Criteria=Total Project
IncludeChildren=1
Scope=All
AllowComplete=1

