[Process001]

ProcessID=Recalc

Project=0473

Criteria=Resource

IncludeChildren=1

Selection=SUB-MFG-LABOR

Scope=All

ClassList=Actual,EA

ResultList=COM,DIRECT,FTE,GANDA,HOURS,ODCNOGA,OH,GACOM

AllowComplete=1

AllowReadOnlyClasses=0

ReplaceResults=0
[Process002]

ProcessID=Recalc

Project=0473

Criteria=Resource

IncludeChildren=1

Selection=ODC

Scope=All

ClassList=Actual,EA

ResultList=COM,DIRECT,FTE,GANDA,HOURS,ODCNOGA,OH,GACOM

AllowComplete=1

AllowReadOnlyClasses=0

ReplaceResults=0